#!/bin/bash

# EMBED BI-RADS prediction
python train.py  \
    --batch_size 36 \
    --learning_rate 4e-5 \
    --experiment_name MaMA_standard_SLA \
    --devices 4 \
    --strategy 'ddp_find_unused_parameters_true' \
    --llm_type gpt \
    --precision bf16-true \
    --peft lora \
    --accumulate_grad_batches 2 \
    --grad_ckpt \
    --weight_decay 0.1 \
    --warm_up 4000 \
    --emb_dim 512 \
    --max_steps 40000 \
    --pool_feat \
    --embed \
    --structural_cap \
    --slip \
    --img_size 518 \
    --crop_size 518 \
    --vit_grad_ckpt \
    --load_jpg \
    --num_workers 8 \
    --mask_ratio 1.0 \
    --mask_meta 0.8 \
    --symmetric_clip \
    --inter_side  \
    --local_contrast \
    --pool_txt_feat \
    --late_loss 8000 \
    --symmetric_local  \
    --pretrained_model $1 \
    --num_classes 7 \
    --balanced_test \
    --instance_test_cap \
    --eval \

# EMBED Density prediction
python train.py  \
    --batch_size 36 \
    --learning_rate 4e-5 \
    --experiment_name MaMA_standard_SLA \
    --devices 4 \
    --strategy 'ddp_find_unused_parameters_true' \
    --llm_type gpt \
    --precision bf16-true \
    --peft lora \
    --accumulate_grad_batches 2 \
    --grad_ckpt \
    --weight_decay 0.1 \
    --warm_up 4000 \
    --emb_dim 512 \
    --max_steps 40000 \
    --pool_feat \
    --embed \
    --structural_cap \
    --slip \
    --img_size 518 \
    --crop_size 518 \
    --vit_grad_ckpt \
    --load_jpg \
    --num_workers 8 \
    --mask_ratio 1.0 \
    --mask_meta 0.8 \
    --symmetric_clip \
    --inter_side  \
    --local_contrast \
    --pool_txt_feat \
    --late_loss 8000 \
    --symmetric_local  \
    --pretrained_model $1 \
    --num_classes 4 \
    --balanced_test \
    --instance_test_cap \
    --eval \
    --pred_density 

# RNSA-Mammo prediction
python train.py  \
    --batch_size 36 \
    --learning_rate 4e-5 \
    --experiment_name MaMA_standard_SLA \
    --devices 4 \
    --strategy 'ddp_find_unused_parameters_true' \
    --llm_type gpt \
    --precision bf16-true \
    --peft lora \
    --accumulate_grad_batches 2 \
    --grad_ckpt \
    --weight_decay 0.1 \
    --warm_up 4000 \
    --emb_dim 512 \
    --max_steps 40000 \
    --pool_feat \
    --rsna_mammo \
    --structural_cap \
    --slip \
    --img_size 518 \
    --crop_size 518 \
    --vit_grad_ckpt \
    --load_jpg \
    --num_workers 8 \
    --mask_ratio 1.0 \
    --mask_meta 0.8 \
    --symmetric_clip \
    --inter_side  \
    --local_contrast \
    --pool_txt_feat \
    --late_loss 8000 \
    --symmetric_local  \
    --pretrained_model $1 \
    --num_classes 2 \
    --instance_test_cap \
    --eval