from train_asym_mirai import main as main_train
from run_eval_bu_asym_mirai import main as eval_main
import torchvision
import torch

# Train AsymMirai and save the resulting model
torch.cuda.set_device(0)
torch.manual_seed(0)

# main_train(device_ids=[0],
#            risk_yr=5,
#            loss_type="CE",
#            model="mirai",
#            label_col="cancer2yr_updated",
#            KD_label="logit",
#            dataset="bu",
#            data_file="/restricted/projectnb/batmanlab/shawn24/PhD/Multimodal-mistakes-debug/src/codebase/MIRAI/Mirai/results/merged_dataframe_MIRAI_BUMC_image_level_mammo-clip_risk.csv",
#            arch="MIRAI",
#            chk_pt="/restricted/projectnb/batmanlab/shawn24/PhD/Multimodal-mistakes-debug/src/codebase/MIRAI/Mirai/snapshots/mgh_mammo_MIRAI_Base_May20_2019.p",
#            batch_size=30,
#            lr=0.005,
#            use_addon_layers=False,
#            use_stretch_matrix=True,
#            initial_asym_mean=2000,  # *20,
#            initial_asym_std=300,
#            flexible_asymmetry=True,
#            max_workers=8,
#            align_images=False,
#            latent_h=5,
#            latent_w=5,
#            save_file_suffix="4_26_alt_ablation_flex_width_5_matrix_learned_dist",
#            use_all_training_data=False,
#            oversample_cancer_rate=None,
#            topk_for_heatmap=None,
#            multiple_pairs_per_exam=False)

## ID BU
# eval_main(device_ids=[0],
#           risk_yr=5,
#           loss_type="CE",
#           model="mirai",
#           label_col="cancer{0}yr_updated",
#           KD_label="logit",
#           dataset="bu",
#           save_dir="/restricted/projectnb/batmanlab/shawn24/PhD/Breast-CLIP-downstream/src/codebase/AsymMirai-master/asymmetry_model/out/bu/MIRAI/loss_CE/risk_yr_{0}_KD_col_logit/training_preds",
#           model_path="full_model_partial_epoch_7_4_26_alt_ablation_flex_width_5_matrix_learned_dist.pt",
#           data_file="/restricted/projectnb/batmanlab/shawn24/PhD/Multimodal-mistakes-debug/src/codebase/MIRAI/Mirai/results/merged_dataframe_MIRAI_BUMC_image_level_mammo-clip_risk.csv",
#           arch="MIRAI",
#           chk_pt="/restricted/projectnb/batmanlab/shawn24/PhD/Multimodal-mistakes-debug/src/codebase/MIRAI/Mirai/snapshots/mgh_mammo_MIRAI_Base_May20_2019.p",
#           batch_size=1,
#           lr=0.005,
#           use_addon_layers=False,
#           use_stretch_matrix=True,
#           initial_asym_mean=2000,  # *20,
#           initial_asym_std=300,
#           flexible_asymmetry=True,
#           max_workers=8,
#           align_images=False,
#           latent_h=5,
#           latent_w=5,
#           save_file_suffix="4_26_alt_ablation_flex_width_5_matrix_learned_dist",
#           use_all_training_data=False,
#           oversample_cancer_rate=None,
#           topk_for_heatmap=None,
#           multiple_pairs_per_exam=False)

## OOD RSNA
eval_main(device_ids=[0],
          risk_yr=5,
          loss_type="CE",
          model="mirai",
          label_col="cancer",
          KD_label="logit",
          dataset="RSNA",
          save_dir="/restricted/projectnb/batmanlab/shawn24/PhD/Breast-CLIP-downstream/src/codebase/AsymMirai-master/asymmetry_model/out/bu/MIRAI/loss_CE/risk_yr_{0}_KD_col_logit/training_preds",
          model_path="full_model_partial_epoch_7_4_26_alt_ablation_flex_width_5_matrix_learned_dist.pt",
          data_file="/restricted/projectnb/batmanlab/shawn24/PhD/Multimodal-mistakes-debug/src/codebase/MIRAI/Mirai/results/merged_dataframe_MIRAI_RSNA_image_level_mammo-clip_risk.csv",
          arch="MIRAI",
          chk_pt="/restricted/projectnb/batmanlab/shawn24/PhD/Multimodal-mistakes-debug/src/codebase/MIRAI/Mirai/snapshots/mgh_mammo_MIRAI_Base_May20_2019.p",
          batch_size=1,
          lr=0.005,
          use_addon_layers=False,
          use_stretch_matrix=True,
          initial_asym_mean=2000,  # *20,
          initial_asym_std=300,
          flexible_asymmetry=True,
          max_workers=8,
          align_images=False,
          latent_h=5,
          latent_w=5,
          save_file_suffix="4_26_alt_ablation_flex_width_5_matrix_learned_dist",
          use_all_training_data=False,
          oversample_cancer_rate=None,
          topk_for_heatmap=None,
          multiple_pairs_per_exam=False)
